sonar.projectKey=revisium_demo-enterprise-catalog-frontend
sonar.organization=revisium
sonar.exclusions=src/__generated__/**,**/__generated__/**,node_modules/**,build/**,dist/**,.react-router/**
sonar.cpd.exclusions=src/__generated__/**,**/__generated__/**,node_modules/**,build/**,dist/**,.react-router/**
sonar.coverage.exclusions=**/*
