sonar.projectKey=revisium_demo-enterprise-catalog-frontend
sonar.organization=revisium
sonar.exclusions=src/__generated__/**,**/__generated__/**
sonar.cpd.exclusions=src/__generated__/**,**/__generated__/**
